import { EUserRole, TNavLinks } from "@/types";

export const navLinks: TNavLinks[] = [
  {
    color: "white",
    icon: "mdi-home",
    name: "HomePage",
    route: EUserRole.PROTECTED,
    url: "/",
    text: "Media-Tracker",
    title: "Home",
  },
  {
    color: "indigo",
    name: "AnimePage",
    icon: "mdi-cat",
    route: EUserRole.PROTECTED,
    url: "/anime",
    text: "Anime",
    title: "Anime",
  },
  {
    color: "purple",
    name: "BooksPage",
    icon: "mdi-book-open-variant",
    route: EUserRole.PROTECTED,
    url: "/books",
    text: "Books",
    title: "Books",
  },
  {
    color: "red",
    name: "CharactersPage",
    icon: "mdi-face-woman",
    route: EUserRole.PROTECTED,
    url: "/characters",
    text: "Characters",
    title: "Characters",
  },
  {
    color: "cyan",
    name: "EmotesPage",
    icon: "mdi-emoticon",
    route: EUserRole.ADMIN,
    url: "/emotes",
    text: "Emotes",
    title: "Emotes",
  },
  {
    color: "amber",
    name: "GamesPage",
    icon: "mdi-gamepad-square",
    route: EUserRole.PROTECTED,
    url: "/games",
    text: "Games",
    title: "Games",
  },
  {
    color: "green",
    name: "MangaPage",
    icon: "mdi-book-account",
    route: EUserRole.PROTECTED,
    url: "/manga",
    text: "Manga",
    title: "Manga",
  },
  {
    color: "yellow",
    name: "MoviesPage",
    icon: "mdi-movie-open",
    route: EUserRole.PROTECTED,
    url: "/movies",
    text: "Movies",
    title: "Movies",
  },
  {
    color: "deep-purple",
    name: "MusicPage",
    icon: "mdi-music",
    route: EUserRole.PROTECTED,
    url: "/music",
    text: "Music",
    title: "Music",
  },
  // {
  //   color: "cyan",
  //   name: "NotesPage",
  //   icon: "mdi-note",
  //   route: EUserRole.PROTECTED,
  //   url: "/notes",
  //   text: "Notes",
  //   title: "Notes",
  // },
  // {
  //   name: "ChartsPage",
  //   route: EUserRole.PROTECTED,
  //   url: "/charts",
  //   text: "Charts",
  //   title: "Charts",
  // },
  // {
  // {
  //   name: "AboutPage",
  //   route: EUserRole.PROTECTED,
  //   url: "/about",
  //   text: "About",
  //   title: "About",
  // },
  {
    color: "blue",
    name: "StatsPage",
    icon: "mdi-chart-bar",
    route: EUserRole.PROTECTED,
    url: "/stats",
    text: "Stats",
    title: "Stats",
  },
];
